name: Hello Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # accepts licenses and installs cmdline-tools; Gradle will fetch platforms/build-tools
          log-accepted-android-sdk-licenses: false

      - name: Create minimal Android project
        run: |
          mkdir -p app/src/main/java/com/example/lenstracker
          cat > settings.gradle <<'EOF'
          rootProject.name="LensTracker"
          include(":app")
          EOF
          cat > build.gradle <<'EOF'
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies {
                  classpath "com.android.tools.build:gradle:8.5.2"
                  classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24"
              }
          }
          EOF
          cat > gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
          android.useAndroidX=true
          android.nonTransitiveRClass=true
          EOF
          mkdir -p app/src/main
          cat > app/build.gradle <<'EOF'
          plugins {
              id 'com.android.application'
              id 'org.jetbrains.kotlin.android'
          }
          android {
              namespace "com.example.lenstracker"
              compileSdk 34
              defaultConfig {
                  applicationId "com.example.lenstracker"
                  minSdk 23
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
              kotlinOptions { jvmTarget="17" }
              buildFeatures { compose true }
              composeOptions { kotlinCompilerExtensionVersion '1.5.14' }
          }
          repositories { google(); mavenCentral() }
          dependencies {
              implementation "androidx.activity:activity-compose:1.9.2"
              implementation "androidx.compose.ui:ui:1.7.4"
              implementation "androidx.compose.material:material:1.7.4"
          }
          EOF
          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:label="LensTracker" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round">
              <activity android:name=".MainActivity" android:exported="true">
                <intent-filter>
                  <action android:name="android.intent.action.MAIN" />
                  <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
              </activity>
            </application>
          </manifest>
          EOF
          cat > app/src/main/java/com/example/lenstracker/MainActivity.kt <<'EOF'
          package com.example.lenstracker
          import android.os.Bundle
          import androidx.activity.ComponentActivity
          import androidx.activity.compose.setContent
          import androidx.compose.material.*
          import androidx.compose.runtime.Composable
          class MainActivity : ComponentActivity() {
              override fun onCreate(savedInstanceState: Bundle?) {
                  super.onCreate(savedInstanceState)
                  setContent { Greeting() }
              }
          }
          @Composable
          fun Greeting() { Text("Hello from LensTracker!") }
          EOF

      - name: Build with Gradle (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug
          build-root-directory: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
